# Keep in sync with .editorconfig
format_strings      = true
group_imports       = "StdExternalCrate"
hard_tabs           = false
imports_granularity = "Crate"
max_width           = 100
tab_spaces          = 2
wrap_comments       = true
