[package]
description = "uora"
edition     = "2021"
license     = "MIT"
name        = "uora"
repository  = "https://github.com/uora/uora"
version     = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi        = { workspace = true }
napi-derive = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
