name: Compressed Size

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
    paths-ignore:
      - 'examples/**'
      - 'docs/**'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-swc:
    permissions:
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: ${{ matrix.target }}

  compressed-size:
    name: 'Compressed Size'
    permissions:
      checks: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    needs:
      - build-swc
    strategy:
      matrix:
        node-version: ['16']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: swc
          path: packages/swc/dist

      - name: Setup PNPM
        uses: ./.github/actions/pnpm
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Packages
        run: pnpm run build

      - uses: preactjs/compressed-size-action@v2
        with:
          build-script: 'build'
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          pattern: './packages/*/{dist,bin}/**/*.{js,cjs,mjs,mustache,d.ts}'
