name: Docs

env:
  NODE_OPTIONS: --max-old-space-size=6144
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: uora

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
    paths:
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-swc:
    permissions:
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: ${{ matrix.target }}

  docs:
    name: 'Docs'
    permissions:
      checks: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    needs:
      - build-swc
    strategy:
      matrix:
        node-version: ['16']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: swc
          path: packages/swc/dist

      - name: Setup PNPM
        uses: ./.github/actions/pnpm
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Vercel CLI
        run: pnpm add --global vercel@canary

      - name: Build Packages
        run: pnpm run build

      - name: Build Doc
        run: pnpm run docs:build

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
